/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedDeploymentRouteImport } from './routes/_authenticated/deployment'
import { Route as AuthenticatedGensetsRouteImport } from './routes/_authenticated/gensets'
import { Route as AuthenticatedMetersRouteImport } from './routes/_authenticated/meters'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedRefuelRouteImport } from './routes/_authenticated/refuel'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSitesRouteImport } from './routes/_authenticated/sites'
import { Route as AuthenticatedGensetsGensetIdRouteImport } from './routes/_authenticated/gensets_.$gensetId'
import { Route as AuthenticatedSitesSiteIdRouteImport } from './routes/_authenticated/sites_.$siteId'
import { Route as AuthenticatedGensetsGensetIdIndexRouteImport } from './routes/_authenticated/gensets_.$gensetId.index'
import { Route as AuthenticatedGensetsGensetIdAlarmsRouteImport } from './routes/_authenticated/gensets_.$gensetId.alarms'
import { Route as AuthenticatedGensetsGensetIdAnalysisRouteImport } from './routes/_authenticated/gensets_.$gensetId.analysis'
import { Route as AuthenticatedGensetsGensetIdDeploymentsRouteImport } from './routes/_authenticated/gensets_.$gensetId.deployments'
import { Route as AuthenticatedGensetsGensetIdEquipmentRouteImport } from './routes/_authenticated/gensets_.$gensetId.equipment'
import { Route as AuthenticatedGensetsGensetIdRefuelRouteImport } from './routes/_authenticated/gensets_.$gensetId.refuel'
import { Route as AuthenticatedGensetsGensetIdRunsRouteImport } from './routes/_authenticated/gensets_.$gensetId.runs'
import { Route as AuthenticatedGensetsGensetIdServiceRouteImport } from './routes/_authenticated/gensets_.$gensetId.service'
import { Route as AuthenticatedGensetsGensetIdSettingsRouteImport } from './routes/_authenticated/gensets_.$gensetId.settings'
import { Route as AuthenticatedSitesSiteIdIndexRouteImport } from './routes/_authenticated/sites_.$siteId.index'
import { Route as AuthenticatedSitesSiteIdAlarmsRouteImport } from './routes/_authenticated/sites_.$siteId.alarms'
import { Route as AuthenticatedSitesSiteIdContractRouteImport } from './routes/_authenticated/sites_.$siteId.contract'
import { Route as AuthenticatedSitesSiteIdRunsRouteImport } from './routes/_authenticated/sites_.$siteId.runs'
import { Route as AuthenticatedSitesSiteIdSettingsRouteImport } from './routes/_authenticated/sites_.$siteId.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDeploymentRoute = AuthenticatedDeploymentRouteImport.update({
  id: '/deployment',
  path: '/deployment',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGensetsRoute = AuthenticatedGensetsRouteImport.update({
  id: '/gensets',
  path: '/gensets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMetersRoute = AuthenticatedMetersRouteImport.update({
  id: '/meters',
  path: '/meters',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRefuelRoute = AuthenticatedRefuelRouteImport.update({
  id: '/refuel',
  path: '/refuel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSitesRoute = AuthenticatedSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGensetsGensetIdRoute =
  AuthenticatedGensetsGensetIdRouteImport.update({
    id: '/gensets_/$gensetId',
    path: '/gensets/$gensetId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSitesSiteIdRoute =
  AuthenticatedSitesSiteIdRouteImport.update({
    id: '/sites_/$siteId',
    path: '/sites/$siteId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGensetsGensetIdIndexRoute =
  AuthenticatedGensetsGensetIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGensetsGensetIdRoute,
  } as any)
const AuthenticatedGensetsGensetIdAlarmsRoute =
  AuthenticatedGensetsGensetIdAlarmsRouteImport.update({
    id: '/alarms',
    path: '/alarms',
    getParentRoute: () => AuthenticatedGensetsGensetIdRoute,
  } as any)
const AuthenticatedGensetsGensetIdAnalysisRoute =
  AuthenticatedGensetsGensetIdAnalysisRouteImport.update({
    id: '/analysis',
    path: '/analysis',
    getParentRoute: () => AuthenticatedGensetsGensetIdRoute,
  } as any)
const AuthenticatedGensetsGensetIdDeploymentsRoute =
  AuthenticatedGensetsGensetIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AuthenticatedGensetsGensetIdRoute,
  } as any)
const AuthenticatedGensetsGensetIdEquipmentRoute =
  AuthenticatedGensetsGensetIdEquipmentRouteImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => AuthenticatedGensetsGensetIdRoute,
  } as any)
const AuthenticatedGensetsGensetIdRefuelRoute =
  AuthenticatedGensetsGensetIdRefuelRouteImport.update({
    id: '/refuel',
    path: '/refuel',
    getParentRoute: () => AuthenticatedGensetsGensetIdRoute,
  } as any)
const AuthenticatedGensetsGensetIdRunsRoute =
  AuthenticatedGensetsGensetIdRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AuthenticatedGensetsGensetIdRoute,
  } as any)
const AuthenticatedGensetsGensetIdServiceRoute =
  AuthenticatedGensetsGensetIdServiceRouteImport.update({
    id: '/service',
    path: '/service',
    getParentRoute: () => AuthenticatedGensetsGensetIdRoute,
  } as any)
const AuthenticatedGensetsGensetIdSettingsRoute =
  AuthenticatedGensetsGensetIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedGensetsGensetIdRoute,
  } as any)
const AuthenticatedSitesSiteIdIndexRoute =
  AuthenticatedSitesSiteIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSitesSiteIdRoute,
  } as any)
const AuthenticatedSitesSiteIdAlarmsRoute =
  AuthenticatedSitesSiteIdAlarmsRouteImport.update({
    id: '/alarms',
    path: '/alarms',
    getParentRoute: () => AuthenticatedSitesSiteIdRoute,
  } as any)
const AuthenticatedSitesSiteIdContractRoute =
  AuthenticatedSitesSiteIdContractRouteImport.update({
    id: '/contract',
    path: '/contract',
    getParentRoute: () => AuthenticatedSitesSiteIdRoute,
  } as any)
const AuthenticatedSitesSiteIdRunsRoute =
  AuthenticatedSitesSiteIdRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AuthenticatedSitesSiteIdRoute,
  } as any)
const AuthenticatedSitesSiteIdSettingsRoute =
  AuthenticatedSitesSiteIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSitesSiteIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/deployment': typeof AuthenticatedDeploymentRoute
  '/gensets': typeof AuthenticatedGensetsRoute
  '/meters': typeof AuthenticatedMetersRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/refuel': typeof AuthenticatedRefuelRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/gensets/$gensetId': typeof AuthenticatedGensetsGensetIdRouteWithChildren
  '/sites/$siteId': typeof AuthenticatedSitesSiteIdRouteWithChildren
  '/gensets/$gensetId/alarms': typeof AuthenticatedGensetsGensetIdAlarmsRoute
  '/gensets/$gensetId/analysis': typeof AuthenticatedGensetsGensetIdAnalysisRoute
  '/gensets/$gensetId/deployments': typeof AuthenticatedGensetsGensetIdDeploymentsRoute
  '/gensets/$gensetId/equipment': typeof AuthenticatedGensetsGensetIdEquipmentRoute
  '/gensets/$gensetId/refuel': typeof AuthenticatedGensetsGensetIdRefuelRoute
  '/gensets/$gensetId/runs': typeof AuthenticatedGensetsGensetIdRunsRoute
  '/gensets/$gensetId/service': typeof AuthenticatedGensetsGensetIdServiceRoute
  '/gensets/$gensetId/settings': typeof AuthenticatedGensetsGensetIdSettingsRoute
  '/sites/$siteId/alarms': typeof AuthenticatedSitesSiteIdAlarmsRoute
  '/sites/$siteId/contract': typeof AuthenticatedSitesSiteIdContractRoute
  '/sites/$siteId/runs': typeof AuthenticatedSitesSiteIdRunsRoute
  '/sites/$siteId/settings': typeof AuthenticatedSitesSiteIdSettingsRoute
  '/gensets/$gensetId/': typeof AuthenticatedGensetsGensetIdIndexRoute
  '/sites/$siteId/': typeof AuthenticatedSitesSiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/deployment': typeof AuthenticatedDeploymentRoute
  '/gensets': typeof AuthenticatedGensetsRoute
  '/meters': typeof AuthenticatedMetersRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/refuel': typeof AuthenticatedRefuelRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/gensets/$gensetId/alarms': typeof AuthenticatedGensetsGensetIdAlarmsRoute
  '/gensets/$gensetId/analysis': typeof AuthenticatedGensetsGensetIdAnalysisRoute
  '/gensets/$gensetId/deployments': typeof AuthenticatedGensetsGensetIdDeploymentsRoute
  '/gensets/$gensetId/equipment': typeof AuthenticatedGensetsGensetIdEquipmentRoute
  '/gensets/$gensetId/refuel': typeof AuthenticatedGensetsGensetIdRefuelRoute
  '/gensets/$gensetId/runs': typeof AuthenticatedGensetsGensetIdRunsRoute
  '/gensets/$gensetId/service': typeof AuthenticatedGensetsGensetIdServiceRoute
  '/gensets/$gensetId/settings': typeof AuthenticatedGensetsGensetIdSettingsRoute
  '/sites/$siteId/alarms': typeof AuthenticatedSitesSiteIdAlarmsRoute
  '/sites/$siteId/contract': typeof AuthenticatedSitesSiteIdContractRoute
  '/sites/$siteId/runs': typeof AuthenticatedSitesSiteIdRunsRoute
  '/sites/$siteId/settings': typeof AuthenticatedSitesSiteIdSettingsRoute
  '/gensets/$gensetId': typeof AuthenticatedGensetsGensetIdIndexRoute
  '/sites/$siteId': typeof AuthenticatedSitesSiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/deployment': typeof AuthenticatedDeploymentRoute
  '/_authenticated/gensets': typeof AuthenticatedGensetsRoute
  '/_authenticated/meters': typeof AuthenticatedMetersRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/refuel': typeof AuthenticatedRefuelRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sites': typeof AuthenticatedSitesRoute
  '/_authenticated/gensets_/$gensetId': typeof AuthenticatedGensetsGensetIdRouteWithChildren
  '/_authenticated/sites_/$siteId': typeof AuthenticatedSitesSiteIdRouteWithChildren
  '/_authenticated/gensets_/$gensetId/alarms': typeof AuthenticatedGensetsGensetIdAlarmsRoute
  '/_authenticated/gensets_/$gensetId/analysis': typeof AuthenticatedGensetsGensetIdAnalysisRoute
  '/_authenticated/gensets_/$gensetId/deployments': typeof AuthenticatedGensetsGensetIdDeploymentsRoute
  '/_authenticated/gensets_/$gensetId/equipment': typeof AuthenticatedGensetsGensetIdEquipmentRoute
  '/_authenticated/gensets_/$gensetId/refuel': typeof AuthenticatedGensetsGensetIdRefuelRoute
  '/_authenticated/gensets_/$gensetId/runs': typeof AuthenticatedGensetsGensetIdRunsRoute
  '/_authenticated/gensets_/$gensetId/service': typeof AuthenticatedGensetsGensetIdServiceRoute
  '/_authenticated/gensets_/$gensetId/settings': typeof AuthenticatedGensetsGensetIdSettingsRoute
  '/_authenticated/sites_/$siteId/alarms': typeof AuthenticatedSitesSiteIdAlarmsRoute
  '/_authenticated/sites_/$siteId/contract': typeof AuthenticatedSitesSiteIdContractRoute
  '/_authenticated/sites_/$siteId/runs': typeof AuthenticatedSitesSiteIdRunsRoute
  '/_authenticated/sites_/$siteId/settings': typeof AuthenticatedSitesSiteIdSettingsRoute
  '/_authenticated/gensets_/$gensetId/': typeof AuthenticatedGensetsGensetIdIndexRoute
  '/_authenticated/sites_/$siteId/': typeof AuthenticatedSitesSiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/deployment'
    | '/gensets'
    | '/meters'
    | '/overview'
    | '/refuel'
    | '/settings'
    | '/sites'
    | '/gensets/$gensetId'
    | '/sites/$siteId'
    | '/gensets/$gensetId/alarms'
    | '/gensets/$gensetId/analysis'
    | '/gensets/$gensetId/deployments'
    | '/gensets/$gensetId/equipment'
    | '/gensets/$gensetId/refuel'
    | '/gensets/$gensetId/runs'
    | '/gensets/$gensetId/service'
    | '/gensets/$gensetId/settings'
    | '/sites/$siteId/alarms'
    | '/sites/$siteId/contract'
    | '/sites/$siteId/runs'
    | '/sites/$siteId/settings'
    | '/gensets/$gensetId/'
    | '/sites/$siteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/deployment'
    | '/gensets'
    | '/meters'
    | '/overview'
    | '/refuel'
    | '/settings'
    | '/sites'
    | '/gensets/$gensetId/alarms'
    | '/gensets/$gensetId/analysis'
    | '/gensets/$gensetId/deployments'
    | '/gensets/$gensetId/equipment'
    | '/gensets/$gensetId/refuel'
    | '/gensets/$gensetId/runs'
    | '/gensets/$gensetId/service'
    | '/gensets/$gensetId/settings'
    | '/sites/$siteId/alarms'
    | '/sites/$siteId/contract'
    | '/sites/$siteId/runs'
    | '/sites/$siteId/settings'
    | '/gensets/$gensetId'
    | '/sites/$siteId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/deployment'
    | '/_authenticated/gensets'
    | '/_authenticated/meters'
    | '/_authenticated/overview'
    | '/_authenticated/refuel'
    | '/_authenticated/settings'
    | '/_authenticated/sites'
    | '/_authenticated/gensets_/$gensetId'
    | '/_authenticated/sites_/$siteId'
    | '/_authenticated/gensets_/$gensetId/alarms'
    | '/_authenticated/gensets_/$gensetId/analysis'
    | '/_authenticated/gensets_/$gensetId/deployments'
    | '/_authenticated/gensets_/$gensetId/equipment'
    | '/_authenticated/gensets_/$gensetId/refuel'
    | '/_authenticated/gensets_/$gensetId/runs'
    | '/_authenticated/gensets_/$gensetId/service'
    | '/_authenticated/gensets_/$gensetId/settings'
    | '/_authenticated/sites_/$siteId/alarms'
    | '/_authenticated/sites_/$siteId/contract'
    | '/_authenticated/sites_/$siteId/runs'
    | '/_authenticated/sites_/$siteId/settings'
    | '/_authenticated/gensets_/$gensetId/'
    | '/_authenticated/sites_/$siteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/deployment': {
      id: '/_authenticated/deployment'
      path: '/deployment'
      fullPath: '/deployment'
      preLoaderRoute: typeof AuthenticatedDeploymentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gensets': {
      id: '/_authenticated/gensets'
      path: '/gensets'
      fullPath: '/gensets'
      preLoaderRoute: typeof AuthenticatedGensetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meters': {
      id: '/_authenticated/meters'
      path: '/meters'
      fullPath: '/meters'
      preLoaderRoute: typeof AuthenticatedMetersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/refuel': {
      id: '/_authenticated/refuel'
      path: '/refuel'
      fullPath: '/refuel'
      preLoaderRoute: typeof AuthenticatedRefuelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sites': {
      id: '/_authenticated/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthenticatedSitesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gensets_/$gensetId': {
      id: '/_authenticated/gensets_/$gensetId'
      path: '/gensets/$gensetId'
      fullPath: '/gensets/$gensetId'
      preLoaderRoute: typeof AuthenticatedGensetsGensetIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sites_/$siteId': {
      id: '/_authenticated/sites_/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gensets_/$gensetId/': {
      id: '/_authenticated/gensets_/$gensetId/'
      path: '/'
      fullPath: '/gensets/$gensetId/'
      preLoaderRoute: typeof AuthenticatedGensetsGensetIdIndexRouteImport
      parentRoute: typeof AuthenticatedGensetsGensetIdRoute
    }
    '/_authenticated/gensets_/$gensetId/alarms': {
      id: '/_authenticated/gensets_/$gensetId/alarms'
      path: '/alarms'
      fullPath: '/gensets/$gensetId/alarms'
      preLoaderRoute: typeof AuthenticatedGensetsGensetIdAlarmsRouteImport
      parentRoute: typeof AuthenticatedGensetsGensetIdRoute
    }
    '/_authenticated/gensets_/$gensetId/analysis': {
      id: '/_authenticated/gensets_/$gensetId/analysis'
      path: '/analysis'
      fullPath: '/gensets/$gensetId/analysis'
      preLoaderRoute: typeof AuthenticatedGensetsGensetIdAnalysisRouteImport
      parentRoute: typeof AuthenticatedGensetsGensetIdRoute
    }
    '/_authenticated/gensets_/$gensetId/deployments': {
      id: '/_authenticated/gensets_/$gensetId/deployments'
      path: '/deployments'
      fullPath: '/gensets/$gensetId/deployments'
      preLoaderRoute: typeof AuthenticatedGensetsGensetIdDeploymentsRouteImport
      parentRoute: typeof AuthenticatedGensetsGensetIdRoute
    }
    '/_authenticated/gensets_/$gensetId/equipment': {
      id: '/_authenticated/gensets_/$gensetId/equipment'
      path: '/equipment'
      fullPath: '/gensets/$gensetId/equipment'
      preLoaderRoute: typeof AuthenticatedGensetsGensetIdEquipmentRouteImport
      parentRoute: typeof AuthenticatedGensetsGensetIdRoute
    }
    '/_authenticated/gensets_/$gensetId/refuel': {
      id: '/_authenticated/gensets_/$gensetId/refuel'
      path: '/refuel'
      fullPath: '/gensets/$gensetId/refuel'
      preLoaderRoute: typeof AuthenticatedGensetsGensetIdRefuelRouteImport
      parentRoute: typeof AuthenticatedGensetsGensetIdRoute
    }
    '/_authenticated/gensets_/$gensetId/runs': {
      id: '/_authenticated/gensets_/$gensetId/runs'
      path: '/runs'
      fullPath: '/gensets/$gensetId/runs'
      preLoaderRoute: typeof AuthenticatedGensetsGensetIdRunsRouteImport
      parentRoute: typeof AuthenticatedGensetsGensetIdRoute
    }
    '/_authenticated/gensets_/$gensetId/service': {
      id: '/_authenticated/gensets_/$gensetId/service'
      path: '/service'
      fullPath: '/gensets/$gensetId/service'
      preLoaderRoute: typeof AuthenticatedGensetsGensetIdServiceRouteImport
      parentRoute: typeof AuthenticatedGensetsGensetIdRoute
    }
    '/_authenticated/gensets_/$gensetId/settings': {
      id: '/_authenticated/gensets_/$gensetId/settings'
      path: '/settings'
      fullPath: '/gensets/$gensetId/settings'
      preLoaderRoute: typeof AuthenticatedGensetsGensetIdSettingsRouteImport
      parentRoute: typeof AuthenticatedGensetsGensetIdRoute
    }
    '/_authenticated/sites_/$siteId/': {
      id: '/_authenticated/sites_/$siteId/'
      path: '/'
      fullPath: '/sites/$siteId/'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdIndexRouteImport
      parentRoute: typeof AuthenticatedSitesSiteIdRoute
    }
    '/_authenticated/sites_/$siteId/alarms': {
      id: '/_authenticated/sites_/$siteId/alarms'
      path: '/alarms'
      fullPath: '/sites/$siteId/alarms'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdAlarmsRouteImport
      parentRoute: typeof AuthenticatedSitesSiteIdRoute
    }
    '/_authenticated/sites_/$siteId/contract': {
      id: '/_authenticated/sites_/$siteId/contract'
      path: '/contract'
      fullPath: '/sites/$siteId/contract'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdContractRouteImport
      parentRoute: typeof AuthenticatedSitesSiteIdRoute
    }
    '/_authenticated/sites_/$siteId/runs': {
      id: '/_authenticated/sites_/$siteId/runs'
      path: '/runs'
      fullPath: '/sites/$siteId/runs'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdRunsRouteImport
      parentRoute: typeof AuthenticatedSitesSiteIdRoute
    }
    '/_authenticated/sites_/$siteId/settings': {
      id: '/_authenticated/sites_/$siteId/settings'
      path: '/settings'
      fullPath: '/sites/$siteId/settings'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdSettingsRouteImport
      parentRoute: typeof AuthenticatedSitesSiteIdRoute
    }
  }
}

interface AuthenticatedGensetsGensetIdRouteChildren {
  AuthenticatedGensetsGensetIdAlarmsRoute: typeof AuthenticatedGensetsGensetIdAlarmsRoute
  AuthenticatedGensetsGensetIdAnalysisRoute: typeof AuthenticatedGensetsGensetIdAnalysisRoute
  AuthenticatedGensetsGensetIdDeploymentsRoute: typeof AuthenticatedGensetsGensetIdDeploymentsRoute
  AuthenticatedGensetsGensetIdEquipmentRoute: typeof AuthenticatedGensetsGensetIdEquipmentRoute
  AuthenticatedGensetsGensetIdRefuelRoute: typeof AuthenticatedGensetsGensetIdRefuelRoute
  AuthenticatedGensetsGensetIdRunsRoute: typeof AuthenticatedGensetsGensetIdRunsRoute
  AuthenticatedGensetsGensetIdServiceRoute: typeof AuthenticatedGensetsGensetIdServiceRoute
  AuthenticatedGensetsGensetIdSettingsRoute: typeof AuthenticatedGensetsGensetIdSettingsRoute
  AuthenticatedGensetsGensetIdIndexRoute: typeof AuthenticatedGensetsGensetIdIndexRoute
}

const AuthenticatedGensetsGensetIdRouteChildren: AuthenticatedGensetsGensetIdRouteChildren =
  {
    AuthenticatedGensetsGensetIdAlarmsRoute:
      AuthenticatedGensetsGensetIdAlarmsRoute,
    AuthenticatedGensetsGensetIdAnalysisRoute:
      AuthenticatedGensetsGensetIdAnalysisRoute,
    AuthenticatedGensetsGensetIdDeploymentsRoute:
      AuthenticatedGensetsGensetIdDeploymentsRoute,
    AuthenticatedGensetsGensetIdEquipmentRoute:
      AuthenticatedGensetsGensetIdEquipmentRoute,
    AuthenticatedGensetsGensetIdRefuelRoute:
      AuthenticatedGensetsGensetIdRefuelRoute,
    AuthenticatedGensetsGensetIdRunsRoute:
      AuthenticatedGensetsGensetIdRunsRoute,
    AuthenticatedGensetsGensetIdServiceRoute:
      AuthenticatedGensetsGensetIdServiceRoute,
    AuthenticatedGensetsGensetIdSettingsRoute:
      AuthenticatedGensetsGensetIdSettingsRoute,
    AuthenticatedGensetsGensetIdIndexRoute:
      AuthenticatedGensetsGensetIdIndexRoute,
  }

const AuthenticatedGensetsGensetIdRouteWithChildren =
  AuthenticatedGensetsGensetIdRoute._addFileChildren(
    AuthenticatedGensetsGensetIdRouteChildren,
  )

interface AuthenticatedSitesSiteIdRouteChildren {
  AuthenticatedSitesSiteIdAlarmsRoute: typeof AuthenticatedSitesSiteIdAlarmsRoute
  AuthenticatedSitesSiteIdContractRoute: typeof AuthenticatedSitesSiteIdContractRoute
  AuthenticatedSitesSiteIdRunsRoute: typeof AuthenticatedSitesSiteIdRunsRoute
  AuthenticatedSitesSiteIdSettingsRoute: typeof AuthenticatedSitesSiteIdSettingsRoute
  AuthenticatedSitesSiteIdIndexRoute: typeof AuthenticatedSitesSiteIdIndexRoute
}

const AuthenticatedSitesSiteIdRouteChildren: AuthenticatedSitesSiteIdRouteChildren =
  {
    AuthenticatedSitesSiteIdAlarmsRoute: AuthenticatedSitesSiteIdAlarmsRoute,
    AuthenticatedSitesSiteIdContractRoute:
      AuthenticatedSitesSiteIdContractRoute,
    AuthenticatedSitesSiteIdRunsRoute: AuthenticatedSitesSiteIdRunsRoute,
    AuthenticatedSitesSiteIdSettingsRoute:
      AuthenticatedSitesSiteIdSettingsRoute,
    AuthenticatedSitesSiteIdIndexRoute: AuthenticatedSitesSiteIdIndexRoute,
  }

const AuthenticatedSitesSiteIdRouteWithChildren =
  AuthenticatedSitesSiteIdRoute._addFileChildren(
    AuthenticatedSitesSiteIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDeploymentRoute: typeof AuthenticatedDeploymentRoute
  AuthenticatedGensetsRoute: typeof AuthenticatedGensetsRoute
  AuthenticatedMetersRoute: typeof AuthenticatedMetersRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedRefuelRoute: typeof AuthenticatedRefuelRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSitesRoute: typeof AuthenticatedSitesRoute
  AuthenticatedGensetsGensetIdRoute: typeof AuthenticatedGensetsGensetIdRouteWithChildren
  AuthenticatedSitesSiteIdRoute: typeof AuthenticatedSitesSiteIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDeploymentRoute: AuthenticatedDeploymentRoute,
  AuthenticatedGensetsRoute: AuthenticatedGensetsRoute,
  AuthenticatedMetersRoute: AuthenticatedMetersRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedRefuelRoute: AuthenticatedRefuelRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSitesRoute: AuthenticatedSitesRoute,
  AuthenticatedGensetsGensetIdRoute:
    AuthenticatedGensetsGensetIdRouteWithChildren,
  AuthenticatedSitesSiteIdRoute: AuthenticatedSitesSiteIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
